var mlist=({data:[{"v":"none","Rft":{"href_mail":function(a){location.href="mailto:"+a.v},"href_src":function(a){location.href="http://at21xx0.github.io/"+a.d}}},["index",["m",{"v":"1.mp3","ft":"href_src","d":"m/1.mp3"}],"index.html","gui.html","music.js","musicj.js"],["Help","this",{"v":"ww"}],["About",["email",{"ft":"href_mail","v":"at21xx0@163.com"},{"ft":"href_mail","v":"at21xx0@qq.com"},{"ft":"href_mail","v":"at21xx0@gmail.com"}]],["test",{v:"ok",f:function(){alert('ok');}}]],
list:function(a,b,c){if(!mlist.ld[b])mlist.ld[b]=["","",2];if(Array.isArray(c)){mlist.ld[b][0]=c;if(!mlist.ld[b][0][0].Rt)mlist.ld[b][0][0].Rt={};if(!mlist.ld[b][0][0].Rf)mlist.ld[b][0][0].Rf={};if(!mlist.ld[b][0][0]["Rt"].fv)mlist.ld[b][0][0]["Rt"].fv=function(a,b,c,d){if(c==0)a.v="Back";if(a.title)a.v=a.title;if(b=="Close"){if(/_list$/.test(d))d=d.replace(/_list$/,"");b="mlist.mlist(0,'"+d+"');";a.v="Close"}return ('<button style="width:100%;height:32px;position:relative;background-color:#DDD;border:1px solid black;font-size:100%;outline:none;" onclick="javascript: '+b+'">'+a.v+'</button>')};}
if(isNaN(a)&&typeof a!="object"){var m='';if(/^\//.test(a)){m=mlist.list(-2,b);a=a.replace(/\//,"");}else{m=mlist.list(-1,b);}while(a){if(!isNaN(a.match(/^[^\/]+/))){m=a.match(/^[0-9]+/)}else{m=m[a.match(/^[^\/]+/)];if(m==undefined)break;}a=a.replace(/^[^\/]+\/?/,"");m=mlist.list(m,b);}if(!a)return;}
if(a==-2)while(mlist.ld[b].length>3){mlist.ld[b].pop()}
if(a==0&&mlist.ld[b].length>3){mlist.ld[b].pop();}else if(a>0){mlist.ld[b].push(a)}mlist.ld[b][1]="";mlist.ld[b][2]=3;while(mlist.ld[b][2]<mlist.ld[b].length){mlist.ld[b][1]+="["+mlist.ld[b][mlist.ld[b][2]]+"]";mlist.ld[b][2]++;}
eval("var data=mlist.ld[b][0]"+mlist.ld[b][1]);if(data.f)data.f(data,m);if(mlist.ld[b][0][0]["Rft"][data.ft])mlist.ld[b][0][0]["Rft"][data.ft](data,m);if(!Array.isArray(data)){mlist.ld[b].pop();return}
var v=mlist.ld[b];var i=0;var value="";var value1="";var func="";var value2={};var l=data.length;
while(i<data.length){
if(!Array.isArray(data[i])){value1=data[i];}else{value1=data[i][0];}if(!value1.v){value1={"v":value1}}value2[value1.v]=i;if(v.length==3&&i==0){func="Close";}else{func="mlist.list("+i+"\,'"+b+"');";}if(!value1.t)value1.t="fv";
value+=v[0][0]["Rt"][value1.t](value1,func,i,b,l);i++}document.getElementById(b).innerHTML=value;return value2},
mlist:function(a,b,c){if(!b)b="mlist";if(a==-1){mlist.ld[b+"_list"]=null;document.body.removeChild(mlist.element[b]);return}if(!mlist.element[b]){if(!c)c=mlist.data;mlist.element[b]=document.createElement("div");if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){var style="top:0;left:0;height:auto;width:100%;position:fixed;"}else{style="top:0;left:30%;height:auto;width:40%;position:fixed;"}
mlist.element[b].setAttribute("id",b);
mlist.element[b].setAttribute("style",style);
mlist.element[b].innerHTML='<div style="width:100%;height:28px;position:relative;"><input type="button" class="G1" style="width:28px;height:100%;position:absolute;" onclick="document.getElementById(\''+a+'_t\').style.display=\'block\'" value="←"><input type="text" style="top:0;left:28px;right:0;height:28px;position:absolute;border:0;font-size:100%;outline:none" placeholder="Some text..." onkeydown="if(event.keyCode===13)if(/^\\s/.test(this.value)){try{eval(this.value)}catch(err){alert(err)}}else{mlist.list_it(this.value)}"><div id="'+b+'_t" style="top:0;left:0;height:28px;width:100%;position:absolute;background-color:#0E0;font-size:125%;text-align:center;" ondblclick="this.style.display=\'none\'">Test</div></div><div id="'+b+'_list" style="width:100%;height:auto;"></div>';
document.body.appendChild(mlist.element[b]);
mlist.list(-2,b+"_list",c);
if(/width:40%/.test(style))mlist.rd(b+"_t",b);}else if(a==0){mlist.element[b].style.display="none";}else if(a==1){mlist.element[b].style.display="block"}else if(typeof a=="string"){mlist.list(a,b+"_list");}},
w:function(a,b,c){if(!b){var i=0;while(!isNaN(i)){i++;if(!mlist.element["w"+i])i="w"+i;}b=i};var e;if(a==-1){mlist.rd(b+"_t",-1);document.body.removeChild(mlist.element[b]);mlist.element[b]=null;return}if(!mlist.element[b]){if(typeof c!="object")c={v:c};if(!c.t)c.t="Untitled";mlist.element[b]=document.createElement("div");if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){var style="width:100%;height:auto;top:0;left:0;background-color:#FFF;position:fixed"}else{var style="top:0;left:30%;background-color:#FFF;height:auto;width:40%;position:fixed;"}mlist.element[b].setAttribute("id",b);mlist.element[b].setAttribute("style",style);mlist.element[b].innerHTML='<div id="'+b+'_u" style="width:100%;min-height:30px;margin-left:0;margin-top:0;position:relative;"><button style="width:30px;height:30px;top:0;right:60px;position:absolute;background-color: #FFF;border:1px solid black;font-size:100%;outline:none;" onclick="mlist.w(0,\''+b+'\');">__</button><button style="width:30px;height:30px;top:0;right:30px;position:absolute;background-color:#FFF;border:1px solid black;font-size:100%;outline:none;" onclick="mlist.w(2,\''+b+'\');">□</button><button style="width:30px;height:30px;right:0;top:0;position:absolute;background-color:#FFF;border:1px solid black;font-size:100%;outline:none;" onclick="javascript: mlist.w(-1,\''+b+'\');">╳</button><div id="'+b+'_t" ondblclick="mlist.w(2,\''+b+'\');" style="height:30px;left:0;right:90px;position:absolute;background-color:#EFB;font-size:120%;border-top:1px solid black;border-left:1px solid black;">'+c.t+'(id: '+b+')'+'</div></div><div id="'+b+'_v" style="width:100%;height:auto;left:0;top:0;position:relative;border:1px solid black;border-top:0;">'+c.v+'</div><button id="'+b+'_b" style="right:5px;top:5px;height:30px;width:30px;position:fixed;display:none;background-color:#444;opacity:.50;font-size:120%;color:black;border:0;outline:none;" onclick="mlist.w(-2,\''+b+'\');">╳</button>';c.t=null;document.body.appendChild(mlist.element[b]);mlist.rd(b+"_t",b);}else if(a==0){mlist.element[b].style.display="none";}else if(a==1){mlist.element[b].style.display="block";}else if(a==2){document.getElementById(b+"_u").style.display="none";document.getElementById(b+"_v").style="width:100%;height:auto;left:0;top:0;position:fixed;background-color:#FFF";document.getElementById(b+"_b").style.display="block";}else if(a==-2){document.getElementById(b+"_v").style="width:100%;height:auto;left:0;top:0;position:relative;border:1px solid black;border-top:0;";document.getElementById(b+"_b").style.display="none";document.getElementById(b+"_u").style.display="block";}if(c.t)document.getElementById(b+"_t").innerHTML=c.t},
o:function(a,b,c){if(typeof a!="object")a={v:a};if(!b){var i=0;while(!isNaN(i)){i++;if(!mlist.element["o"+i])i="o"+i;}b=i};if(!/\s/.test(a.v)&&/\.[A-Za-z0-9]+/.test(a.v)&&!/^\//.test(a.v)&&!/^\./.test(a.v)||/^data:/.test(a.v)||a.v=="u"){if(/\.(bmp|jpg|jepg|png|gif)$/i.test(a.v)||/^data:image/i.test(a.v)||a.t=="image"){if(!a.title)a.title="Picture";mlist.w(1,null,{v:'<img height="auto" width="100%" src="'+a.v+'">',t:a.title});}else if(/\.(mp4|flv|u3m8)$/i.test(a.v)||a.t=="video"){if(!a.title)a.title="video";mlist.w(1,null,{v:'<video width="100%" height="auto" controls="controls" controls="controls"><source src="'+a.v+'"></video>',t:a.title});}else if(/\.(mp3|m4a|flac|ogg)$/i.test(a.v)||a.t=="audio"){if(!a.title)a.title="Audio";mlist.w(1,null,{t:a.title,v:'<audio width="100%" height="auto" src="'+a.v+'" controls="controls">'});}else if(/\.js$/i.test(a.v)||a.t=="script"){if(!c)c=1;if(c==1){mlist.element[b]=document.createElement("script");mlist.element[b].setAttribute("type","text/javascript");mlist.element[b].setAttribute("src",a.v);document.body.appendChild(mlist.element[b]);}else if(c==-1){document.body.removeChild(mlist.element[b]);mlist.element[b]=null;}}else if(/\.css$/i.test(a.v)||a.t=="style"){if(!c)c=1;if(c==1){mlist.element[b]=document.createElement("style");mlist.element[b].setAttribute("type","text/css");mlist.element[b].setAttribute("src",a.v);document.body.appendChild(mlist.element[b]);}else if(c==-1){document.body.removeChild(mlist.element[b]);mlist.element[b]=null;}}else if(/\.(html|htm)$/i.test(a.v)||a.t=="page"){if(!a.title)a.title="Page";mlist.w(1,null,{t:a.title,v:'<iframe width="100%" height="auto" src="'+a.v+'">'});}}},
list_itd:{"Page":{"help":"help.html","at21xx0":"http:\/\/at21xx0.github.io","bing":"https:\/\/cn.bing.com","music":"http://at21xx0.github.com/Pm.html"},"s 1":"http:\/\/cn.bing.com/search?q=","help":"mlist.list_it('Page help')"},list_itF:{"F":function(a){eval(a.replace(/^[^\s]+\s/,''))},".":function(a){location.href=a},"/":function(a){if(/^\/index$/.test(a)||/^\/index\//.test(a)){if(a=="/index")a=="/index/";mlist.list(a.replace(/\/index/,''),"")}else{location.href=a.replace(/\//,'')}},"Help":function(a){mlist.list_it("Page help");},"P":function(a){mlist.list_it(a.replace(/^[^\s]+/,"Page"))},"Page":function(a){location.href=mlist.list_itd[a.match(/^[^\s]+/)][a.replace(/^[^\s]+\s/,'')]}},list_it:function(a){try{if(!/\s/.test(a)&&/\.[A-Za-z0-9]+/.test(a)&&!/^\//.test(a)&&!/^\./.test(a)){if(/^[^\s]+\:\/\/[^\s]*/.test(a)){location.href=a;}else{location.href="http\:\/\/"+a;}}else if(mlist.list_itF[a.match(/^[^\s]+/)]!=undefined||/^\//.test(a)||/^\./.test(a)){if(/^\//.test(a)){mlist.list_itF["/"](a)}else if(/^\./.test(a)){mlist.list_itF["."](a)}else{mlist.list_itF[a.match(/^[^\s]+/)](a)}}else{location.href=mlist.list_itd["s 1"]+encodeURIComponent(a);}}catch(err){alert(err);}},
rd:function(a,b){mlist.rdd[a]={e:document.getElementById(a)};if(b==-1&&mlist.rdd[a]){mlist.rdd[a].e.removeEventListener("touchstart",mlist.rdd[a].s,true);mlist.rdd[a].e.removeEventListener("touchmove",mlist.rdd[a].m,false);mlist.rdd[a]=null;return;}if(b){mlist.rdd[a].c=document.getElementById(b);b="c"}else{b="e"};eval('mlist.rdd["'+a+'"].s=function(event){mlist.rdd["'+a+'"].x=event.targetTouches[0].pageX-window.getComputedStyle(mlist.rdd["'+a+'"]["'+b+'"]).left.match(/[0-9\\-\\.]+/);mlist.rdd["'+a+'"].y=event.targetTouches[0].pageY-window.getComputedStyle(mlist.rdd["'+a+'"]["'+b+'"]).top.match(/[0-9\\-\\.]+/);};mlist.rdd["'+a+'"].m=function(event){event.preventDefault();mlist.rdd["'+a+'"]["'+b+'"].style.left=(event.changedTouches[0].pageX-mlist.rdd["'+a+'"].x)+"px";mlist.rdd["'+a+'"]["'+b+'"].style.top=(event.changedTouches[0].pageY-mlist.rdd["'+a+'"].y)+"px";};');mlist.rdd[a].e.addEventListener("touchstart",mlist.rdd[a].s,false);mlist.rdd[a].e.addEventListener("touchmove",mlist.rdd[a].m,false);},rdd:{},start:function(a,b){if(!b)b="mlist";mlist.element[b+"_u"]=document.createElement("div");mlist.element[b+"_u"].setAttribute("id",b+"_u");mlist.element[b+"_u"].setAttribute("style","right:0;top:0;width:48px;height:48px;padding:0;background-image: url('data:image/gif;base64,R0lGODlhQABAAPAAAAAAAAAAACH5BAEAAAEALAAAAABAAEAAAAL+jI+py+0PI5i0gojzsrxfDTbeyIVmQKbeialuyYrvbMXKK6v2kYK9TWIFhavd6FTc8TqhpHIJazGftynESUVgGdZstfboomg6bXRzNpDLZjDaDV1vxW3KW04fV7hpNX6rt/dld/cnODiBmOiVIdbHGAYXuAgpdeh3WRl5madZSPnoyXcYimmYmRBVOnn6MUrI6tAqmeq2OotaB0qr2ypryxs3+0saLKoo7HpMDNu5bAob+/xKCa083Vubi53WiRvdey2teEotznr+XZ18Ph5u+JmDqi7uTEdPzgzu6cy+3M+u3ZMjEgACWUVOYAxAm4whMWhunwmCDxkWtNhoSEYcigfZJETog55DIvg0lTxWDps1FyojbmsJMyaIAgA7');background-size:100%;position:fixed");mlist.element[b+"_u"].setAttribute("onclick","mlist.mlist(1,'"+b+"');");document.body.appendChild(mlist.element[b+"_u"]);mlist.rd(b+"_u");},
GetF:function(url){var xmlhttp;if(window.XMLHttpRequest){xmlhttp=new XMLHttpRequest();}else{xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");}/*xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4&&xmlhttp.status==200){value=xmlhttp.responseText;}};*/xmlhttp.open("GET",url,false);xmlhttp.send();if(xmlhttp.readyState==4&&xmlhttp.status==200){return xmlhttp.responseText}else{xmlhttp.status}},
Dfile:function(a,b){var c=document.createElement("a");c.setAttribute("href","data:text/plain;charset=utf-8," + encodeURIComponent(b));c.setAttribute("download",a);c.style.display="none";document.body.appendChild(c);c.click();document.body.removeChild(c);},
Rfile:function(event,func){var file=event.target.files[0];var reader=new FileReader();reader.onload=function(event){func(event.target.result)};reader.readAsText(file);},ld:{},element:{}});
mlist.start(0,"uu");
//mlist.w(0,"dd",'<input type="text" onkeydown="if(event.keyCode==13)eval(this.value);">');
//alert(mlist.GetF("http://quan.suning.com/getSysTime.do"))
//alert("ok");
//Esc